enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

enum ACCOUNT_ENUM {
  PENDING = 'PENDING',
  VERIFY = 'VERIFY',
  REJECT = 'REJECT',
  DELETED = 'DELETED',
  ACTIVE = 'ACTIVE',
}

enum TYPE_FILE_ENUM {
  PROFILE = 'PROFILE',
  CARD_FRONT = 'CARD_FRONT',
  CARD_BACK = 'CARD_BACK',
  PASSPORT = 'PASSPORT',
  DRIVER = 'DRIVER',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
}

enum DOCUMENT_ENUM {
  IDENTITY_CARD = 'IDENTITY_CARD',
  PASSPORT = 'PASSPORT',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
}

enum PRODUCT_TYPE_FILTER {
  LASTED = `LASTED`,
  BESTSELLTER = `BESTSELLTER`,
  HOTSALE = `HOTSALE`,
  RELATED = `RELATED`,
  RECOMMAND = `RECOMMAND`,
}

export {
  STATUS,
  ACCOUNT_ENUM,
  TYPE_FILE_ENUM,
  DOCUMENT_ENUM,
  PRODUCT_TYPE_FILTER,
};
