const MSG = {
  TOKEN_EXPIRED: `TOKEN_EXPIRED`,
  INVALID_TOKEN: `INVALID_TOKEN`,
  INVALID_USERNAME_PW: `INVLID_USERNAME_PW`,
  NOT_FOUND: `NOT_FOUND`,
  NOT_FOUND_ACCOUNT: `NOT_FOUND_ACCOUNT`,
  LOGOUT_SUCCESS: `LOGOUT_SUCCESS`,
  UPDATE_SUCCESS: `UPDATE_SUCCESS`,
  REMOVE_SUCCESS: `REMOVE_SUCCESS`,
  INVALID_CREATED: `INVALID_CREATED`,
  INVALID_UPDATED: `INVALID_UPDATED`,
  INVALID_ACCOUNT: `INVALID_ACCOUNT`,
  INVALID_PASSOWRD: `INVALID_PASSOWRD`,
  FILE_NOT_FOUND: `FILE_NOT_FOUND`,
  NOT_FOUND_ACCOUNT_VERIFY: `NOT_FOUND_ACCOUNT_VERIFY`,
  INVALID_UPDATED_ACCOUNT_VERIFY: `INVALID_UPDATED_ACCOUNT_VERIFY`,
};

export { MSG };
